### ISSUE TITLE
Optically thin radiative cooling

### ISSUE THREAD

**Issue by dutta-alankar** [idefix-code/idefix#14]
@glesur @neutrinoceros Would you be interested if I develop optically thin radiative cooling from any say Cloudy generated tabulated cooling table in `Idefix`?

**Comment by glesur** [comment]
@dutta-alankar : I assume you mean something similar to the cooling functions implemented in Pluto? This could be handy. Note however that there are already tools to load and use tabulated data in Idefix (just use the `LookupTable` class), so there is no need to duplicate that part (see example in test/utils/lookupTable)

**Comment by dutta-alankar** [comment]
Yes similar to cooling functions on PLUTO. I also have implemented the Townsend integration of cooling in PLUTO which isn't there in the original PLUTO releases. I would then also try to implement that. @glesur Thanks for pointing at the relevant sections of the code.

**Comment by glesur** [comment]
Unless there's something planned on this implementation from @dutta-alankar , I propose to close this issue.

**Comment by dutta-alankar** [comment]
I have plans of putting this in. But you may close this issue right now as I am currently busy with postdoc applications and many other stuffs. I have plans of working on this at around the summer of 2024. Since this is a long time from now, you may close this. I can anyways open a new PR implementing optically thin radiative cooling with Townsend integration.

**Comment by glesur** [comment]
Ok, thanks @dutta-alankar ! Good luck with your postdoc applications.

**Comment by dutta-alankar** [comment]
@glesur Thanks!
