### ISSUE TITLE
Issue with Compiling Basic Test Problems for IDEFIX V2.0.01 ?

### ISSUE THREAD

**Issue by matthewjoroberts** [idefix-code/idefix#204]
### Question

With the most recent version of IDEFIX, I am finding that the ability to compile a simple test problem (say the MHD/disc problem) is dependent on the system.

Locally, on a single CPU on a macbook, or a single core on the DAMTP Fawcett system the code compiles and runs.

However, on the main system I use (CSD3 cluster) the code does not compile on any of the nodes. The output from running the make -j 8 command is in the build.log file attached

[build.log](https://github.com/idefix-code/idefix/files/13240797/build.log)

I am also having this issue for V2.0.00 as well. Please let me know if I can provide any further information and thank you for all the help.

**Comment by glesur** [comment]
Can you tell me which compiler+version this is using?

**Comment by matthewjoroberts** [comment]
The compiler+version is GNU 8.5.0 (see attached log)

[cmake.log](https://github.com/idefix-code/idefix/files/13243746/cmake.log)

Thanks!

**Comment by matthewjoroberts** [comment]
Hi Geoff,

This is fixed by loading a newer compiler, say GNU 9.4.0. Thanks

**Comment by glesur** [comment]
A PR is on its way for gcc8 (see above)
