### ISSUE TITLE
Mac install

### ISSUE THREAD

**Issue by johnsonbryanmark** [idefix-code/idefix#232]
### Question

I'm trying to install idefix on a 2023 MacBook Pro (OS Ventura, M2 Max processor) and am getting the error below during install. (The idefix 'cmake $IDEFIX_DIR' command was proceeded by 'brew install openmp' and 'brew install libomp', and I've tried it with both -DIdefix_MPI=ON` and `-DKokkos_ENABLE_OPENMP=ON'). Any suggestions?

CMake Error at /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
   Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
 Call Stack (most recent call first):
   /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
   /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindOpenMP.cmake:577 (find_package_handle_standard_args)
   src/kokkos/cmake/kokkos_tpls.cmake:102 (find_package)
   src/kokkos/cmake/kokkos_tribits.cmake:207 (INCLUDE)
   src/kokkos/CMakeLists.txt:226 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

**Comment by glesur** [comment]
No feedback for the last 2 weeks, so I'll assume the issue is fixed.
