### ISSUE TITLE
Typo bug in the AddNonIdealMHDFlux function

### ISSUE THREAD

**Issue by jeankpf** [idefix-code/idefix#242]
Hello there,

I noticed a weird line in the AddNonIdealMHDFlux function of the current master branch. 
https://github.com/idefix-code/idefix/blob/158f2aa3a35148bb2a992ae24bb8f813a5965034/src/fluid/addNonIdealMHDFlux.hpp#L261
I think it should rather be something like:
`    localdmax += eta; `
to be consistent with the meaning of the dMax array, and the rest of the code in this function.

Cheers,
Jean

**Comment by glesur** [comment]
Thanks @jeankpf for spotting this!
