### ISSUE TITLE
BUG: misuse of the haveOutput variable in the python binding module

### ISSUE THREAD

**Issue by jeankpf** [idefix-code/idefix#275]
### Describe the issue:

The variable haveInitFlow and haveOutput have been confused in the following line, resulting in the impossible initialisation of the flow with a python function without the entry output_function in the initialisation file.
https://github.com/idefix-code/idefix/blob/a92732f3683af37bc3e55a9e8954867b1ae43967/src/pydefix.cpp#L136

### runtime information:

Commit a92732f

**Comment by glesur** [comment]
fixed in #275
