### ISSUE TITLE
MNT: changing the default target branch to `develop`

### ISSUE THREAD

**Issue by neutrinoceros** [idefix-code/idefix#280]
I'm just now understanding why I so often get things mixed up when I open a PR against the wrong branch:
`master` is still the default branch (as far as I understand, but I don't have sufficient permission to go and check in settings).
It would help if `develop` was made the default branch.

**Comment by glesur** [comment]
The idea is that 
- 1  master is the default branch for people who simply pull or scroll the code (this should be the production branch). 
- 2 PR should be merged with develop, from which new releases to master are being cherry-picked.

We can't set the default to develop, otherwise 1- won't work

**Comment by neutrinoceros** [comment]
Oh I remember now. 5am me cannot be trusted with remembering this workflow that is absolutely orthogonal to the dominant paradigm in my own culture[^1], but from what I understand yours is _also_ the dominant paradigm... in the C++ world, which makes more sense for idefix.
Anyway, I don't see a solution for 5am me so let's close this and hope he won't get confused again.
Sorry about the noise !

[^1]: by which I mean the (scientific) Python ecosystem
